# Copyright 2015 Google
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#      http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Vagrant.configure("2") do |config|

  config.vm.box = "gce"
  config.vm.provider :google do |google, override|
    google.google_project_id = "<project id>"
    google.google_client_email = "<service acct email>"
    google.google_json_key_location = "<acct json file>"

    override.ssh.username = "<username>"
    override.ssh.private_key_path = "<pkey.json>"
    google.image = "ubuntu-1404-trusty-v20150909a"
    google.machine_type = "n1-standard-1"
    google.zone = "us-central1-f"
    google.name = "hashiconf-gce-#{Time.now.to_i}"
    google.scopes = ["devstorage.full_control"]
  end
end
