Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 9393, host: 9393
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "hyperspace-be.sh"
  config.vm.provision "shell", path: "hyperspace-fe.sh"
end
